name: frigo_recettes
description: "Application de génération de recettes basées sur le contenu du frigo."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Versions stables et testées pour Flutter 3.19.x
  image_picker: ^1.0.7
  google_generative_ai: ^0.2.2
  google_mobile_ads: ^4.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
