name: Compile mon APK Flutter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4

    - name: Configurer Java (Forcer Java 11 pour Gradle 7)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Configurer Flutter (Version rétro-compatible)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Nettoyer et générer le projet Android
      run: |
        flutter clean
        flutter create . --platforms=android --org com.frigorecettes

    - name: Forcer la configuration des propriétés Android
      run: |
        echo "android.useAndroidX=true" > android/gradle.properties
        echo "android.enableJetifier=true" >> android/gradle.properties

    - name: Récupérer les dépendances
      run: flutter pub get

    - name: Compiler l'APK en mode Release
      run: flutter build apk --release
      
    - name: Sauvegarder l'APK pour le télécharger
      uses: actions/upload-artifact@v4
      with:
        name: MonApplicationFrigoRecettes
        path: build/app/outputs/flutter-apk/app-release.apk
