name: Compile mon APK Flutter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Étape de boost : On double la mémoire allouée au moteur de compilation
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4

    - name: Configurer Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Configurer Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Nettoyer et générer le projet Android
      run: |
        flutter clean
        flutter create . --platforms=android --org com.frigorecettes

    - name: Forcer les propriétés Android et la version Kotlin
      run: |
        echo "android.useAndroidX=true" > android/gradle.properties
        echo "android.enableJetifier=true" >> android/gradle.properties
        
        # Désactivation de R8 lourd pour éviter le manque de mémoire
        echo "android.enableR8.libraries=false" >> android/gradle.properties
        echo "android.enableR8=false" >> android/gradle.properties
        
        # Mise à jour automatique de la version de Kotlin
        sed -i "s/ext.kotlin_version = .*/ext.kotlin_version = '1.9.20'/g" android/build.gradle

    - name: Récupérer les dépendances
      run: flutter pub get

    - name: Compiler l'APK en mode Release
      run: flutter build apk --release
      
    - name: Sauvegarder l'APK pour le télécharger
      uses: actions/upload-artifact@v4
      with:
        name: MonApplicationFrigoRecettes
        path: build/app/outputs/flutter-apk/app-release.apk
